# docker-compose.yml
version: "3"
services:
  sagemaker-pytorch-notebook:
    image: ${DOCKER_IMAGE}
    container_name: "${DOCKER_CONTAINER}"
    command: ["--no-browser"]
    ports:
      - 8888:8888
    environment:
      JUPYTERLAB_SETTINGS_DIR: "${JUPYTERLAB_SETTINGS_DIR}"
    volumes:
      - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro # For pseudo docker-in-docker
      - ${PROJECT}:${DOCKER_PROJECT} # Project
      - ${JUPYTERLAB_SETTINGS_DIR}:${JUPYTERLAB_SETTINGS_DIR}
